import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Montserrat} from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const inter = Inter({ subsets: ['latin'] })
const Gilory = localFont({
  src: [
    {
      path: '../../assets/fonts/Gilroy-Regular.ttf',
      weight: '400',
    },
    {
      path: '../../assets/fonts/Gilroy-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../assets/fonts/Gilroy-SemiBold.ttf',
      weight: '600',
    },
    {
      path: '../../assets/fonts/Gilroy-Bold.ttf',
      weight: '700',
    },
  ],
  variable:'--font-gilory'
})

const monts = Montserrat({ 
  variable:'--font-montserrat',
  subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${Gilory.variable} ${monts.variable}`}>{children}</body>
    </html>
  )
}


