import type { Metadata } from 'next'
import { Inter, Nunito,PT_Sans } from 'next/font/google'
import { Poppins } from 'next/font/google';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Outfit } from 'next/font/google'
import './globals.css';
import localFont from 'next/font/local';

const inter = Inter({ subsets: ['latin'] })
const Gilory = localFont({
  src: [
    {
      path: '../../assets/fonts/Gilroy-Regular.ttf',
      weight: '400',
    },
    {
      path: '../../assets/fonts/Gilroy-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../assets/fonts/Gilroy-SemiBold.ttf',
      weight: '600',
    },
    {
      path: '../../assets/fonts/Gilroy-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-gilory'
})



const plus = Plus_Jakarta_Sans({
  variable: '--font-plus-Jakarta-Sans',
  subsets: ['latin']
})

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin']
})

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight:['100','200','300','400','500','600','700','800','900']
})
const ptSans = PT_Sans({
  variable: '--font-ptSans',
  subsets: ['latin'],
  weight:['400','700']
})

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight:['200','300','400','500','600','700','800','900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${Gilory.variable} ${plus.variable} ${outfit.variable} ${poppins.variable} ${ptSans.variable} ${nunito.variable}`}>{children}</body>
    </html>
  )
}


